services:
  mysql:
    image: mysql:8.0
    container_name: film-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: tongminh1510
      MYSQL_DATABASE: film_archive
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: film-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minhtong
      MINIO_ROOT_PASSWORD: tongminh1510
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
  minio-data:
